apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: myapp
        image: hello-world
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"